<?php

use Illuminate\Database\Seeder;

class LgasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('lgas')->insert([
            ['name' => "Aba north", 'state_id'=>'1'],
            ['name' => "Aba south", 'state_id'=>'1'],
            ['name' => "Arochukwu", 'state_id'=>'1'],
            ['name' => "Bende", 'state_id'=>'1'],
            ['name' => "Ikwuano", 'state_id'=>'1'],
            ['name' => "Isiala ngwa north", 'state_id'=>'1'],
            ['name' => "Isiala ngwa south", 'state_id'=>'1'],
            ['name' => "Isuikwuato", 'state_id'=>'1'],
            ['name' => "Obingwa", 'state_id'=>'1'],
            ['name' => "Ohafia", 'state_id'=>'1'],
            ['name' => "Osisioma", 'state_id'=>'1'],
            ['name' => "Ugwunagbo", 'state_id'=>'1'],
            ['name' => "Ukwa west", 'state_id'=>'1'],
            ['name' => "Ukwa east", 'state_id'=>'1'],
            ['name' => "Umu - nneochi", 'state_id'=>'1'],
            ['name' => "Umuahia south", 'state_id'=>'1'],
            ['name' => "Umuahia north", 'state_id'=>'1'],
            ['name' => "Demsa", 'state_id'=>'2'],
            ['name' => "Fufore", 'state_id'=>'2'],
            ['name' => "Ganye", 'state_id'=>'2'],
            ['name' => "Gire 1", 'state_id'=>'2'],
            ['name' => "Gombi", 'state_id'=>'2'],
            ['name' => "Guyuk", 'state_id'=>'2'],
            ['name' => "Hong", 'state_id'=>'2'],
            ['name' => "Jada", 'state_id'=>'2'],
            ['name' => "Lamurde", 'state_id'=>'2'],
            ['name' => "Madagali", 'state_id'=>'2'],
            ['name' => "Maiha", 'state_id'=>'2'],
            ['name' => "Mayo - belwa", 'state_id'=>'2'],
            ['name' => "Michika", 'state_id'=>'2'],
            ['name' => "Mubi north", 'state_id'=>'2'],
            ['name' => "Mubi south", 'state_id'=>'2'],
            ['name' => "Numan", 'state_id'=>'2'],
            ['name' => "Shelleng", 'state_id'=>'2'],
            ['name' => "Song", 'state_id'=>'2'],
            ['name' => "Toungo", 'state_id'=>'2'],
            ['name' => "Yola north", 'state_id'=>'2'],
            ['name' => "Yola south", 'state_id'=>'2'],
            ['name' => "Abak", 'state_id'=>'3'],
            ['name' => "Eastern obolo", 'state_id'=>'3'],
            ['name' => "Eket", 'state_id'=>'3'],
            ['name' => "Esit eket (uquo)", 'state_id'=>'3'],
            ['name' => "Essien udim", 'state_id'=>'3'],
            ['name' => "Etim ekpo", 'state_id'=>'3'],
            ['name' => "Etinan", 'state_id'=>'3'],
            ['name' => "Ibeno", 'state_id'=>'3'],
            ['name' => "Ibesikpo asutan", 'state_id'=>'3'],
            ['name' => "Ibiono ibom", 'state_id'=>'3'],
            ['name' => "Ika", 'state_id'=>'3'],
            ['name' => "Ikono", 'state_id'=>'3'],
            ['name' => "Ikot abasi", 'state_id'=>'3'],
            ['name' => "Ikot ekpene", 'state_id'=>'3'],
            ['name' => "Ini", 'state_id'=>'3'],
            ['name' => "Itu", 'state_id'=>'3'],
            ['name' => "Mbo", 'state_id'=>'3'],
            ['name' => "Mkpat enin", 'state_id'=>'3'],
            ['name' => "Nsit atai", 'state_id'=>'3'],
            ['name' => "Nsit ibom", 'state_id'=>'3'],
            ['name' => "Nsit ubium", 'state_id'=>'3'],
            ['name' => "Obot akara", 'state_id'=>'3'],
            ['name' => "Okobo", 'state_id'=>'3'],
            ['name' => "Onna", 'state_id'=>'3'],
            ['name' => "Oron", 'state_id'=>'3'],
            ['name' => "Oruk anam", 'state_id'=>'3'],
            ['name' => "Udung uko", 'state_id'=>'3'],
            ['name' => "Ukanafun", 'state_id'=>'3'],
            ['name' => "Uruan", 'state_id'=>'3'],
            ['name' => "Urue offong oruko", 'state_id'=>'3'],
            ['name' => "Uyo", 'state_id'=>'3'],
            ['name' => "Aguata", 'state_id'=>'4'],
            ['name' => "Anambra east", 'state_id'=>'4'],
            ['name' => "Anambra west", 'state_id'=>'4'],
            ['name' => "Anaocha", 'state_id'=>'4'],
            ['name' => "Awka north", 'state_id'=>'4'],
            ['name' => "Awka south", 'state_id'=>'4'],
            ['name' => "Ayamelum", 'state_id'=>'4'],
            ['name' => "Dunukofia", 'state_id'=>'4'],
            ['name' => "Ekwusigo", 'state_id'=>'4'],
            ['name' => "Idemili north", 'state_id'=>'4'],
            ['name' => "Idemili-south", 'state_id'=>'4'],
            ['name' => "Ihala", 'state_id'=>'4'],
            ['name' => "Njikoka", 'state_id'=>'4'],
            ['name' => "Nnewi north", 'state_id'=>'4'],
            ['name' => "Nnewi south", 'state_id'=>'4'],
            ['name' => "Ogbaru", 'state_id'=>'4'],
            ['name' => "Onitsha -south", 'state_id'=>'4'],
            ['name' => "Onitsha-north", 'state_id'=>'4'],
            ['name' => "Orumba south", 'state_id'=>'4'],
            ['name' => "Orumba north", 'state_id'=>'4'],
            ['name' => "Oyi", 'state_id'=>'4'],
            ['name' => "Alkaleri", 'state_id'=>'5'],
            ['name' => "Bauchi", 'state_id'=>'5'],
            ['name' => "Bogoro", 'state_id'=>'5'],
            ['name' => "Dambam", 'state_id'=>'5'],
            ['name' => "Darazo", 'state_id'=>'5'],
            ['name' => "Dass", 'state_id'=>'5'],
            ['name' => "Gamawa", 'state_id'=>'5'],
            ['name' => "Ganjuwa", 'state_id'=>'5'],
            ['name' => "Giade", 'state_id'=>'5'],
            ['name' => "Itas/gadau", 'state_id'=>'5'],
            ['name' => "Jama'are", 'state_id'=>'5'],
            ['name' => "Katagum", 'state_id'=>'5'],
            ['name' => "Kirfi", 'state_id'=>'5'],
            ['name' => "Misau", 'state_id'=>'5'],
            ['name' => "Ningi", 'state_id'=>'5'],
            ['name' => "Shira", 'state_id'=>'5'],
            ['name' => "Tafawa balewa", 'state_id'=>'5'],
            ['name' => "Toro", 'state_id'=>'5'],
            ['name' => "Warji", 'state_id'=>'5'],
            ['name' => "Zaki", 'state_id'=>'5'],
            ['name' => "Brass", 'state_id'=>'6'],
            ['name' => "Ekeremor", 'state_id'=>'6'],
            ['name' => "Kolokuma/opokuma", 'state_id'=>'6'],
            ['name' => "Nembe", 'state_id'=>'6'],
            ['name' => "Ogbia", 'state_id'=>'6'],
            ['name' => "Sagbama", 'state_id'=>'6'],
            ['name' => "Southern ijaw", 'state_id'=>'6'],
            ['name' => "Yenagoa", 'state_id'=>'6'],
            ['name' => "Ado", 'state_id'=>'7'],
            ['name' => "Agatu", 'state_id'=>'7'],
            ['name' => "Apa", 'state_id'=>'7'],
            ['name' => "Buruku", 'state_id'=>'7'],
            ['name' => "Gboko", 'state_id'=>'7'],
            ['name' => "Guma", 'state_id'=>'7'],
            ['name' => "Gwer east", 'state_id'=>'7'],
            ['name' => "Gwer west", 'state_id'=>'7'],
            ['name' => "Katsina-ala", 'state_id'=>'7'],
            ['name' => "Konshisha", 'state_id'=>'7'],
            ['name' => "Kwande", 'state_id'=>'7'],
            ['name' => "Logo", 'state_id'=>'7'],
            ['name' => "Makurdi", 'state_id'=>'7'],
            ['name' => "Obi", 'state_id'=>'7'],
            ['name' => "Ogbadibo", 'state_id'=>'7'],
            ['name' => "Ohimini", 'state_id'=>'7'],
            ['name' => "Oju", 'state_id'=>'7'],
            ['name' => "Okpokwu", 'state_id'=>'7'],
            ['name' => "Otukpo", 'state_id'=>'7'],
            ['name' => "Tarka", 'state_id'=>'7'],
            ['name' => "Ukum", 'state_id'=>'7'],
            ['name' => "Ushongo", 'state_id'=>'7'],
            ['name' => "Vandeikya", 'state_id'=>'7'],
            ['name' => "Abadam", 'state_id'=>'8'],
            ['name' => "Askira / uba", 'state_id'=>'8'],
            ['name' => "Bama", 'state_id'=>'8'],
            ['name' => "Bayo", 'state_id'=>'8'],
            ['name' => "Biu", 'state_id'=>'8'],
            ['name' => "Chibok", 'state_id'=>'8'],
            ['name' => "Damboa", 'state_id'=>'8'],
            ['name' => "Dikwa", 'state_id'=>'8'],
            ['name' => "Gubio", 'state_id'=>'8'],
            ['name' => "Guzamala", 'state_id'=>'8'],
            ['name' => "Gwoza", 'state_id'=>'8'],
            ['name' => "Hawul", 'state_id'=>'8'],
            ['name' => "Jere", 'state_id'=>'8'],
            ['name' => "Kaga", 'state_id'=>'8'],
            ['name' => "Kala balge", 'state_id'=>'8'],
            ['name' => "Konduga", 'state_id'=>'8'],
            ['name' => "Kukawa", 'state_id'=>'8'],
            ['name' => "Kwaya / kusar", 'state_id'=>'8'],
            ['name' => "Mafa", 'state_id'=>'8'],
            ['name' => "Magumeri", 'state_id'=>'8'],
            ['name' => "Maiduguri m. c.", 'state_id'=>'8'],
            ['name' => "Marte", 'state_id'=>'8'],
            ['name' => "Mobbar", 'state_id'=>'8'],
            ['name' => "Monguno", 'state_id'=>'8'],
            ['name' => "Ngala", 'state_id'=>'8'],
            ['name' => "Nganzai", 'state_id'=>'8'],
            ['name' => "Shani", 'state_id'=>'8'],
            ['name' => "Abi", 'state_id'=>'9'],
            ['name' => "Akamkpa", 'state_id'=>'9'],
            ['name' => "Akpabuyo", 'state_id'=>'9'],
            ['name' => "Bakassi", 'state_id'=>'9'],
            ['name' => "Bekwarra", 'state_id'=>'9'],
            ['name' => "Biase", 'state_id'=>'9'],
            ['name' => "Boki", 'state_id'=>'9'],
            ['name' => "Calabar municipality", 'state_id'=>'9'],
            ['name' => "Calabar south", 'state_id'=>'9'],
            ['name' => "Etung", 'state_id'=>'9'],
            ['name' => "Ikom", 'state_id'=>'9'],
            ['name' => "Obanliku", 'state_id'=>'9'],
            ['name' => "Obubra", 'state_id'=>'9'],
            ['name' => "Obudu", 'state_id'=>'9'],
            ['name' => "Odukpani", 'state_id'=>'9'],
            ['name' => "Ogoja", 'state_id'=>'9'],
            ['name' => "Yakurr", 'state_id'=>'9'],
            ['name' => "Yala", 'state_id'=>'9'],
            ['name' => "Aniocha - south", 'state_id'=>'10'],
            ['name' => "Aniocha north", 'state_id'=>'10'],
            ['name' => "Bomadi", 'state_id'=>'10'],
            ['name' => "Burutu", 'state_id'=>'10'],
            ['name' => "Ethiope east", 'state_id'=>'10'],
            ['name' => "Ethiope west", 'state_id'=>'10'],
            ['name' => "Ika - south", 'state_id'=>'10'],
            ['name' => "Ika north- east", 'state_id'=>'10'],
            ['name' => "Isoko north", 'state_id'=>'10'],
            ['name' => "Isoko south", 'state_id'=>'10'],
            ['name' => "Ndokwa east", 'state_id'=>'10'],
            ['name' => "Ndokwa west", 'state_id'=>'10'],
            ['name' => "Okpe", 'state_id'=>'10'],
            ['name' => "Oshimili - north", 'state_id'=>'10'],
            ['name' => "Oshimili - south", 'state_id'=>'10'],
            ['name' => "Patani", 'state_id'=>'10'],
            ['name' => "Sapele", 'state_id'=>'10'],
            ['name' => "Udu", 'state_id'=>'10'],
            ['name' => "Ughelli north", 'state_id'=>'10'],
            ['name' => "Ughelli south", 'state_id'=>'10'],
            ['name' => "Ukwuani", 'state_id'=>'10'],
            ['name' => "Uvwie", 'state_id'=>'10'],
            ['name' => "Warri north", 'state_id'=>'10'],
            ['name' => "Warri south", 'state_id'=>'10'],
            ['name' => "Warri south west", 'state_id'=>'10'],
            ['name' => "Abakaliki", 'state_id'=>'11'],
            ['name' => "Afikpo south", 'state_id'=>'11'],
            ['name' => "Afikpo north", 'state_id'=>'11'],
            ['name' => "Ebonyi", 'state_id'=>'11'],
            ['name' => "Ezza north", 'state_id'=>'11'],
            ['name' => "Ezza south", 'state_id'=>'11'],
            ['name' => "Ikwo", 'state_id'=>'11'],
            ['name' => "Ishielu", 'state_id'=>'11'],
            ['name' => "Ivo", 'state_id'=>'11'],
            ['name' => "Izzi", 'state_id'=>'11'],
            ['name' => "Ohaozara", 'state_id'=>'11'],
            ['name' => "Ohaukwu", 'state_id'=>'11'],
            ['name' => "Onicha", 'state_id'=>'11'],
            ['name' => "Akoko edo", 'state_id'=>'12'],
            ['name' => "Egor", 'state_id'=>'12'],
            ['name' => "Esan central", 'state_id'=>'12'],
            ['name' => "Esan north east", 'state_id'=>'12'],
            ['name' => "Esan south east", 'state_id'=>'12'],
            ['name' => "Esan west", 'state_id'=>'12'],
            ['name' => "Etsako west", 'state_id'=>'12'],
            ['name' => "Etsako central", 'state_id'=>'12'],
            ['name' => "Etsako east", 'state_id'=>'12'],
            ['name' => "Igueben", 'state_id'=>'12'],
            ['name' => "Ikpoba/okha", 'state_id'=>'12'],
            ['name' => "Oredo", 'state_id'=>'12'],
            ['name' => "Orhionmwon", 'state_id'=>'12'],
            ['name' => "Ovia north east", 'state_id'=>'12'],
            ['name' => "Ovia south west", 'state_id'=>'12'],
            ['name' => "Owan east", 'state_id'=>'12'],
            ['name' => "Owan west", 'state_id'=>'12'],
            ['name' => "Uhunmwode", 'state_id'=>'12'],
            ['name' => "Ado ekiti", 'state_id'=>'13'],
            ['name' => "Efon", 'state_id'=>'13'],
            ['name' => "Ekiti east", 'state_id'=>'13'],
            ['name' => "Ekiti south west", 'state_id'=>'13'],
            ['name' => "Ekiti west", 'state_id'=>'13'],
            ['name' => "Emure", 'state_id'=>'13'],
            ['name' => "Gbonyin", 'state_id'=>'13'],
            ['name' => "Ido / osi", 'state_id'=>'13'],
            ['name' => "Ijero", 'state_id'=>'13'],
            ['name' => "Ikere", 'state_id'=>'13'],
            ['name' => "Ikole", 'state_id'=>'13'],
            ['name' => "Ilejemeje", 'state_id'=>'13'],
            ['name' => "Irepodun / ifelodun", 'state_id'=>'13'],
            ['name' => "Ise / orun", 'state_id'=>'13'],
            ['name' => "Moba", 'state_id'=>'13'],
            ['name' => "Oye", 'state_id'=>'13'],
            ['name' => "Aninri", 'state_id'=>'14'],
            ['name' => "Awgu", 'state_id'=>'14'],
            ['name' => "Enugu east", 'state_id'=>'14'],
            ['name' => "Enugu north", 'state_id'=>'14'],
            ['name' => "Enugu south", 'state_id'=>'14'],
            ['name' => "Ezeagu", 'state_id'=>'14'],
            ['name' => "Igbo etiti", 'state_id'=>'14'],
            ['name' => "Igbo eze north", 'state_id'=>'14'],
            ['name' => "Igbo eze south", 'state_id'=>'14'],
            ['name' => "Isi uzo", 'state_id'=>'14'],
            ['name' => "Nkanu east", 'state_id'=>'14'],
            ['name' => "Nkanu west", 'state_id'=>'14'],
            ['name' => "Nsukka", 'state_id'=>'14'],
            ['name' => "Oji-river", 'state_id'=>'14'],
            ['name' => "Udenu", 'state_id'=>'14'],
            ['name' => "Udi", 'state_id'=>'14'],
            ['name' => "Uzo-uwani", 'state_id'=>'14'],
            ['name' => "Abaji", 'state_id'=>'15'],
            ['name' => "Bwari", 'state_id'=>'15'],
            ['name' => "Gwagwalada", 'state_id'=>'15'],
            ['name' => "Kuje", 'state_id'=>'15'],
            ['name' => "Kwali", 'state_id'=>'15'],
            ['name' => "Municipal", 'state_id'=>'15'],
            ['name' => "Akko", 'state_id'=>'16'],
            ['name' => "Balanga", 'state_id'=>'16'],
            ['name' => "Billiri", 'state_id'=>'16'],
            ['name' => "Dukku", 'state_id'=>'16'],
            ['name' => "Funakaye", 'state_id'=>'16'],
            ['name' => "Gombe", 'state_id'=>'16'],
            ['name' => "Kaltungo", 'state_id'=>'16'],
            ['name' => "Kwami", 'state_id'=>'16'],
            ['name' => "Nafada", 'state_id'=>'16'],
            ['name' => "Shongom", 'state_id'=>'16'],
            ['name' => "Yalmaltu/ deba", 'state_id'=>'16'],
            ['name' => "Aboh mbaise", 'state_id'=>'17'],
            ['name' => "Ahiazu mbaise", 'state_id'=>'17'],
            ['name' => "Ehime mbano", 'state_id'=>'17'],
            ['name' => "Ezinihitte mbaise", 'state_id'=>'17'],
            ['name' => "Ideato north", 'state_id'=>'17'],
            ['name' => "Ideato south", 'state_id'=>'17'],
            ['name' => "Ihitte/uboma (isinweke)", 'state_id'=>'17'],
            ['name' => "Ikeduru (iho)", 'state_id'=>'17'],
            ['name' => "Isiala mbano (umuelemai)", 'state_id'=>'17'],
            ['name' => "Isu (umundugba)", 'state_id'=>'17'],
            ['name' => "Mbaitoli (nwaorieubi)", 'state_id'=>'17'],
            ['name' => "Ngor okpala (umuneke)", 'state_id'=>'17'],
            ['name' => "Njaba (nnenasa)", 'state_id'=>'17'],
            ['name' => "Nkwerre", 'state_id'=>'17'],
            ['name' => "Nwangele (onu-nwangele amaigbo)", 'state_id'=>'17'],
            ['name' => "Obowo (otoko)", 'state_id'=>'17'],
            ['name' => "Oguta (oguta)", 'state_id'=>'17'],
            ['name' => "Ohaji/egbema (mmahu-egbema)", 'state_id'=>'17'],
            ['name' => "Okigwe (okigwe)", 'state_id'=>'17'],
            ['name' => "Onuimo (okwe)", 'state_id'=>'17'],
            ['name' => "Orlu", 'state_id'=>'17'],
            ['name' => "Orsu (awo idemili)", 'state_id'=>'17'],
            ['name' => "Oru west (mgbidi)", 'state_id'=>'17'],
            ['name' => "Oru-east", 'state_id'=>'17'],
            ['name' => "Owerri north (orie uratta)", 'state_id'=>'17'],
            ['name' => "Owerri urban (owerri)", 'state_id'=>'17'],
            ['name' => "Owerri west (umuguma)", 'state_id'=>'17'],
            ['name' => "Auyo", 'state_id'=>'18'],
            ['name' => "Babura", 'state_id'=>'18'],
            ['name' => "Birnin kudu", 'state_id'=>'18'],
            ['name' => "Birniwa", 'state_id'=>'18'],
            ['name' => "Buji", 'state_id'=>'18'],
            ['name' => "Dutse", 'state_id'=>'18'],
            ['name' => "Gagarawa", 'state_id'=>'18'],
            ['name' => "Garki", 'state_id'=>'18'],
            ['name' => "Gumel", 'state_id'=>'18'],
            ['name' => "Guri", 'state_id'=>'18'],
            ['name' => "Gwaram", 'state_id'=>'18'],
            ['name' => "Gwiwa", 'state_id'=>'18'],
            ['name' => "Hadejia", 'state_id'=>'18'],
            ['name' => "Jahun", 'state_id'=>'18'],
            ['name' => "Kafin hausa", 'state_id'=>'18'],
            ['name' => "Kaugama", 'state_id'=>'18'],
            ['name' => "Kazaure", 'state_id'=>'18'],
            ['name' => "Kirika samma", 'state_id'=>'18'],
            ['name' => "Kiyawa", 'state_id'=>'18'],
            ['name' => "Maigatari", 'state_id'=>'18'],
            ['name' => "Malam madori", 'state_id'=>'18'],
            ['name' => "Miga", 'state_id'=>'18'],
            ['name' => "Ringim", 'state_id'=>'18'],
            ['name' => "Roni", 'state_id'=>'18'],
            ['name' => "Sule-tankarkar", 'state_id'=>'18'],
            ['name' => "Taura", 'state_id'=>'18'],
            ['name' => "Yankwashi", 'state_id'=>'18'],
            ['name' => "Birnin gwari", 'state_id'=>'19'],
            ['name' => "Chikun", 'state_id'=>'19'],
            ['name' => "Giwa", 'state_id'=>'19'],
            ['name' => "Igabi", 'state_id'=>'19'],
            ['name' => "Ikara", 'state_id'=>'19'],
            ['name' => "Jaba", 'state_id'=>'19'],
            ['name' => "Jema'a", 'state_id'=>'19'],
            ['name' => "Kachia", 'state_id'=>'19'],
            ['name' => "Kaduna north", 'state_id'=>'19'],
            ['name' => "Kaduna south", 'state_id'=>'19'],
            ['name' => "Kagarko", 'state_id'=>'19'],
            ['name' => "Kajuru", 'state_id'=>'19'],
            ['name' => "Kaura", 'state_id'=>'19'],
            ['name' => "Kauru", 'state_id'=>'19'],
            ['name' => "Kubau", 'state_id'=>'19'],
            ['name' => "Kudan", 'state_id'=>'19'],
            ['name' => "Lere", 'state_id'=>'19'],
            ['name' => "Makarfi", 'state_id'=>'19'],
            ['name' => "Sabon gari", 'state_id'=>'19'],
            ['name' => "Sanga", 'state_id'=>'19'],
            ['name' => "Soba", 'state_id'=>'19'],
            ['name' => "Zangon kataf", 'state_id'=>'19'],
            ['name' => "Zaria", 'state_id'=>'19'],
            ['name' => "Ajingi", 'state_id'=>'20'],
            ['name' => "Albasu", 'state_id'=>'20'],
            ['name' => "Bagwai", 'state_id'=>'20'],
            ['name' => "Bebeji", 'state_id'=>'20'],
            ['name' => "Bichi", 'state_id'=>'20'],
            ['name' => "Bunkure", 'state_id'=>'20'],
            ['name' => "Dala", 'state_id'=>'20'],
            ['name' => "Danbata", 'state_id'=>'20'],
            ['name' => "Dawaki kudu", 'state_id'=>'20'],
            ['name' => "Dawaki tofa", 'state_id'=>'20'],
            ['name' => "Doguwa", 'state_id'=>'20'],
            ['name' => "Fagge", 'state_id'=>'20'],
            ['name' => "Gabasawa", 'state_id'=>'20'],
            ['name' => "Garko", 'state_id'=>'20'],
            ['name' => "Garun malam", 'state_id'=>'20'],
            ['name' => "Gaya", 'state_id'=>'20'],
            ['name' => "Gezawa", 'state_id'=>'20'],
            ['name' => "Gwale", 'state_id'=>'20'],
            ['name' => "Gwarzo", 'state_id'=>'20'],
            ['name' => "Kabo", 'state_id'=>'20'],
            ['name' => "Kano municipal", 'state_id'=>'20'],
            ['name' => "Karaye", 'state_id'=>'20'],
            ['name' => "Kibiya", 'state_id'=>'20'],
            ['name' => "Kiru", 'state_id'=>'20'],
            ['name' => "Kumbotso", 'state_id'=>'20'],
            ['name' => "Kunchi", 'state_id'=>'20'],
            ['name' => "Kura", 'state_id'=>'20'],
            ['name' => "Madobi", 'state_id'=>'20'],
            ['name' => "Makoda", 'state_id'=>'20'],
            ['name' => "Minjibir", 'state_id'=>'20'],
            ['name' => "Nasarawa", 'state_id'=>'20'],
            ['name' => "Rano", 'state_id'=>'20'],
            ['name' => "Rimin gado", 'state_id'=>'20'],
            ['name' => "Rogo", 'state_id'=>'20'],
            ['name' => "Shanono", 'state_id'=>'20'],
            ['name' => "Sumaila", 'state_id'=>'20'],
            ['name' => "Takai", 'state_id'=>'20'],
            ['name' => "Tarauni", 'state_id'=>'20'],
            ['name' => "Tofa", 'state_id'=>'20'],
            ['name' => "Tsanyawa", 'state_id'=>'20'],
            ['name' => "Tudun wada", 'state_id'=>'20'],
            ['name' => "Ungogo", 'state_id'=>'20'],
            ['name' => "Warawa", 'state_id'=>'20'],
            ['name' => "Wudil", 'state_id'=>'20'],
            ['name' => "Bakori", 'state_id'=>'21'],
            ['name' => "Batagarawa", 'state_id'=>'21'],
            ['name' => "Batsari", 'state_id'=>'21'],
            ['name' => "Baure", 'state_id'=>'21'],
            ['name' => "Bindawa", 'state_id'=>'21'],
            ['name' => "Charanchi", 'state_id'=>'21'],
            ['name' => "Dan musa", 'state_id'=>'21'],
            ['name' => "Dandume", 'state_id'=>'21'],
            ['name' => "Danja", 'state_id'=>'21'],
            ['name' => "Daura", 'state_id'=>'21'],
            ['name' => "Dutsi", 'state_id'=>'21'],
            ['name' => "Dutsin-ma", 'state_id'=>'21'],
            ['name' => "Faskari", 'state_id'=>'21'],
            ['name' => "Funtua", 'state_id'=>'21'],
            ['name' => "Ingawa", 'state_id'=>'21'],
            ['name' => "Jibia", 'state_id'=>'21'],
            ['name' => "Kafur", 'state_id'=>'21'],
            ['name' => "Kaita", 'state_id'=>'21'],
            ['name' => "Kankara", 'state_id'=>'21'],
            ['name' => "Kankia", 'state_id'=>'21'],
            ['name' => "Katsina", 'state_id'=>'21'],
            ['name' => "Kurfi", 'state_id'=>'21'],
            ['name' => "Kusada", 'state_id'=>'21'],
            ['name' => "Mai'adua", 'state_id'=>'21'],
            ['name' => "Malufashi", 'state_id'=>'21'],
            ['name' => "Mani", 'state_id'=>'21'],
            ['name' => "Mashi", 'state_id'=>'21'],
            ['name' => "Matazu", 'state_id'=>'21'],
            ['name' => "Musawa", 'state_id'=>'21'],
            ['name' => "Rimi", 'state_id'=>'21'],
            ['name' => "Sabuwa", 'state_id'=>'21'],
            ['name' => "Safana", 'state_id'=>'21'],
            ['name' => "Sandamu", 'state_id'=>'21'],
            ['name' => "Zango", 'state_id'=>'21'],
            ['name' => "Aliero", 'state_id'=>'22'],
            ['name' => "Arewa", 'state_id'=>'22'],
            ['name' => "Argungu", 'state_id'=>'22'],
            ['name' => "Augie", 'state_id'=>'22'],
            ['name' => "Bagudo", 'state_id'=>'22'],
            ['name' => "Birnin kebbi", 'state_id'=>'22'],
            ['name' => "Bunza", 'state_id'=>'22'],
            ['name' => "Dandi", 'state_id'=>'22'],
            ['name' => "Fakai", 'state_id'=>'22'],
            ['name' => "Gwandu", 'state_id'=>'22'],
            ['name' => "Jega", 'state_id'=>'22'],
            ['name' => "Kalgo", 'state_id'=>'22'],
            ['name' => "Koko/besse", 'state_id'=>'22'],
            ['name' => "Maiyama", 'state_id'=>'22'],
            ['name' => "Ngaski", 'state_id'=>'22'],
            ['name' => "Sakaba", 'state_id'=>'22'],
            ['name' => "Shanga", 'state_id'=>'22'],
            ['name' => "Suru", 'state_id'=>'22'],
            ['name' => "Wasagu/danko", 'state_id'=>'22'],
            ['name' => "Yauri", 'state_id'=>'22'],
            ['name' => "Zuru", 'state_id'=>'22'],
            ['name' => "Adavi", 'state_id'=>'23'],
            ['name' => "Ajaokuta", 'state_id'=>'23'],
            ['name' => "Ankpa", 'state_id'=>'23'],
            ['name' => "Bassa", 'state_id'=>'23'],
            ['name' => "Dekina", 'state_id'=>'23'],
            ['name' => "Ibaji", 'state_id'=>'23'],
            ['name' => "Idah", 'state_id'=>'23'],
            ['name' => "Igalamela/odolu", 'state_id'=>'23'],
            ['name' => "Ijumu", 'state_id'=>'23'],
            ['name' => "Kabba/bunu", 'state_id'=>'23'],
            ['name' => "Kogi . k. k.", 'state_id'=>'23'],
            ['name' => "Lokoja", 'state_id'=>'23'],
            ['name' => "Mopa moro", 'state_id'=>'23'],
            ['name' => "Ofu", 'state_id'=>'23'],
            ['name' => "Ogori mangogo", 'state_id'=>'23'],
            ['name' => "Okehi", 'state_id'=>'23'],
            ['name' => "Okene", 'state_id'=>'23'],
            ['name' => "Olamaboro", 'state_id'=>'23'],
            ['name' => "Omala", 'state_id'=>'23'],
            ['name' => "Yagba east", 'state_id'=>'23'],
            ['name' => "Yagba west", 'state_id'=>'23'],
            ['name' => "Asa", 'state_id'=>'24'],
            ['name' => "Baruten", 'state_id'=>'24'],
            ['name' => "Edu", 'state_id'=>'24'],
            ['name' => "Ekiti", 'state_id'=>'24'],
            ['name' => "Ifelodun", 'state_id'=>'24'],
            ['name' => "Ilorin east", 'state_id'=>'24'],
            ['name' => "Ilorin-south", 'state_id'=>'24'],
            ['name' => "Ilorin-west", 'state_id'=>'24'],
            ['name' => "Irepodun", 'state_id'=>'24'],
            ['name' => "Isin", 'state_id'=>'24'],
            ['name' => "Kaiama", 'state_id'=>'24'],
            ['name' => "Moro", 'state_id'=>'24'],
            ['name' => "Offa", 'state_id'=>'24'],
            ['name' => "Oke - ero", 'state_id'=>'24'],
            ['name' => "Oyun", 'state_id'=>'24'],
            ['name' => "Patigi", 'state_id'=>'24'],
            ['name' => "Agege", 'state_id'=>'25'],
            ['name' => "Ajeromi/ifelodun", 'state_id'=>'25'],
            ['name' => "Alimosho", 'state_id'=>'25'],
            ['name' => "Amuwo-odofin", 'state_id'=>'25'],
            ['name' => "Apapa", 'state_id'=>'25'],
            ['name' => "Badagry", 'state_id'=>'25'],
            ['name' => "Epe", 'state_id'=>'25'],
            ['name' => "Eti-osa", 'state_id'=>'25'],
            ['name' => "Ibeju/lekki", 'state_id'=>'25'],
            ['name' => "Ifako-ijaye", 'state_id'=>'25'],
            ['name' => "Ikeja", 'state_id'=>'25'],
            ['name' => "Ikorodu", 'state_id'=>'25'],
            ['name' => "Kosofe", 'state_id'=>'25'],
            ['name' => "Lagos island", 'state_id'=>'25'],
            ['name' => "Lagos mainland", 'state_id'=>'25'],
            ['name' => "Mushin", 'state_id'=>'25'],
            ['name' => "Ojo", 'state_id'=>'25'],
            ['name' => "Oshodi/isolo", 'state_id'=>'25'],
            ['name' => "Somolu", 'state_id'=>'25'],
            ['name' => "Surulere", 'state_id'=>'25'],
            ['name' => "Akwanga", 'state_id'=>'26'],
            ['name' => "Awe", 'state_id'=>'26'],
            ['name' => "Doma", 'state_id'=>'26'],
            ['name' => "Karu", 'state_id'=>'26'],
            ['name' => "Keana", 'state_id'=>'26'],
            ['name' => "Keffi", 'state_id'=>'26'],
            ['name' => "Kokona", 'state_id'=>'26'],
            ['name' => "Lafia", 'state_id'=>'26'],
            ['name' => "Nasarawa", 'state_id'=>'26'],
            ['name' => "Nasarawa eggon", 'state_id'=>'26'],
            ['name' => "Obi", 'state_id'=>'26'],
            ['name' => "Toto", 'state_id'=>'26'],
            ['name' => "Wamba", 'state_id'=>'26'],
            ['name' => "Agaie", 'state_id'=>'27'],
            ['name' => "Agwara", 'state_id'=>'27'],
            ['name' => "Bida", 'state_id'=>'27'],
            ['name' => "Borgu", 'state_id'=>'27'],
            ['name' => "Bosso", 'state_id'=>'27'],
            ['name' => "Chanchaga", 'state_id'=>'27'],
            ['name' => "Edatti", 'state_id'=>'27'],
            ['name' => "Gbako", 'state_id'=>'27'],
            ['name' => "Gurara", 'state_id'=>'27'],
            ['name' => "Katcha", 'state_id'=>'27'],
            ['name' => "Kontagora", 'state_id'=>'27'],
            ['name' => "Lapai", 'state_id'=>'27'],
            ['name' => "Lavun", 'state_id'=>'27'],
            ['name' => "Magama", 'state_id'=>'27'],
            ['name' => "Mariga", 'state_id'=>'27'],
            ['name' => "Mashegu", 'state_id'=>'27'],
            ['name' => "Mokwa", 'state_id'=>'27'],
            ['name' => "Munya", 'state_id'=>'27'],
            ['name' => "Paikoro", 'state_id'=>'27'],
            ['name' => "Rafi", 'state_id'=>'27'],
            ['name' => "Rijau", 'state_id'=>'27'],
            ['name' => "Shiroro", 'state_id'=>'27'],
            ['name' => "Suleja", 'state_id'=>'27'],
            ['name' => "Tafa", 'state_id'=>'27'],
            ['name' => "Wushishi", 'state_id'=>'27'],
            ['name' => "Abeokuta north", 'state_id'=>'28'],
            ['name' => "Abeokuta south", 'state_id'=>'28'],
            ['name' => "Ado odo-ota", 'state_id'=>'28'],
            ['name' => "Egbado north", 'state_id'=>'28'],
            ['name' => "Egbado south", 'state_id'=>'28'],
            ['name' => "Ewekoro", 'state_id'=>'28'],
            ['name' => "Ifo", 'state_id'=>'28'],
            ['name' => "Ijebu east", 'state_id'=>'28'],
            ['name' => "Ijebu north", 'state_id'=>'28'],
            ['name' => "Ijebu north east", 'state_id'=>'28'],
            ['name' => "Ijebu ode", 'state_id'=>'28'],
            ['name' => "Ikenne", 'state_id'=>'28'],
            ['name' => "Imeko/afon", 'state_id'=>'28'],
            ['name' => "Ipokia", 'state_id'=>'28'],
            ['name' => "Obafemi/owode", 'state_id'=>'28'],
            ['name' => "Odeda", 'state_id'=>'28'],
            ['name' => "Odogbolu", 'state_id'=>'28'],
            ['name' => "Ogun water side", 'state_id'=>'28'],
            ['name' => "Remo north", 'state_id'=>'28'],
            ['name' => "Sagamu", 'state_id'=>'28'],
            ['name' => "Akoko north east", 'state_id'=>'29'],
            ['name' => "Akoko north west", 'state_id'=>'29'],
            ['name' => "Akoko south east", 'state_id'=>'29'],
            ['name' => "Akoko south west", 'state_id'=>'29'],
            ['name' => "Akure north", 'state_id'=>'29'],
            ['name' => "Akure south", 'state_id'=>'29'],
            ['name' => "Ese-odo", 'state_id'=>'29'],
            ['name' => "Idanre", 'state_id'=>'29'],
            ['name' => "Ifedore", 'state_id'=>'29'],
            ['name' => "Ilaje", 'state_id'=>'29'],
            ['name' => "Ileoluji/okeigbo", 'state_id'=>'29'],
            ['name' => "Irele", 'state_id'=>'29'],
            ['name' => "Odigbo", 'state_id'=>'29'],
            ['name' => "Okitipupa", 'state_id'=>'29'],
            ['name' => "Ondo east", 'state_id'=>'29'],
            ['name' => "Ondo west", 'state_id'=>'29'],
            ['name' => "Ose", 'state_id'=>'29'],
            ['name' => "Owo", 'state_id'=>'29'],
            ['name' => "Atakumosa east", 'state_id'=>'30'],
            ['name' => "Atakumosa west", 'state_id'=>'30'],
            ['name' => "Ayedaade", 'state_id'=>'30'],
            ['name' => "Ayedire", 'state_id'=>'30'],
            ['name' => "Boluwaduro", 'state_id'=>'30'],
            ['name' => "Boripe", 'state_id'=>'30'],
            ['name' => "Ede north", 'state_id'=>'30'],
            ['name' => "Ede south", 'state_id'=>'30'],
            ['name' => "Egbedore", 'state_id'=>'30'],
            ['name' => "Ejigbo", 'state_id'=>'30'],
            ['name' => "Ife central", 'state_id'=>'30'],
            ['name' => "Ife east", 'state_id'=>'30'],
            ['name' => "Ife north", 'state_id'=>'30'],
            ['name' => "Ife south", 'state_id'=>'30'],
            ['name' => "Ifedayo", 'state_id'=>'30'],
            ['name' => "Ifelodun", 'state_id'=>'30'],
            ['name' => "Ila", 'state_id'=>'30'],
            ['name' => "Ilesa east", 'state_id'=>'30'],
            ['name' => "Ilesa west", 'state_id'=>'30'],
            ['name' => "Irepodun", 'state_id'=>'30'],
            ['name' => "Irewole", 'state_id'=>'30'],
            ['name' => "Isokan", 'state_id'=>'30'],
            ['name' => "Iwo", 'state_id'=>'30'],
            ['name' => "Obokun", 'state_id'=>'30'],
            ['name' => "Odo-otin", 'state_id'=>'30'],
            ['name' => "Ola-oluwa", 'state_id'=>'30'],
            ['name' => "Olorunda", 'state_id'=>'30'],
            ['name' => "Oriade", 'state_id'=>'30'],
            ['name' => "Orolu", 'state_id'=>'30'],
            ['name' => "Osogbo", 'state_id'=>'30'],
            ['name' => "Afijio", 'state_id'=>'31'],
            ['name' => "Akinyele", 'state_id'=>'31'],
            ['name' => "Atiba", 'state_id'=>'31'],
            ['name' => "Atisbo", 'state_id'=>'31'],
            ['name' => "Egbeda", 'state_id'=>'31'],
            ['name' => "Ibadan north", 'state_id'=>'31'],
            ['name' => "Ibadan north east", 'state_id'=>'31'],
            ['name' => "Ibadan north west", 'state_id'=>'31'],
            ['name' => "Ibadan south west", 'state_id'=>'31'],
            ['name' => "Ibadan south-east", 'state_id'=>'31'],
            ['name' => "Ibarapa central", 'state_id'=>'31'],
            ['name' => "Ibarapa east", 'state_id'=>'31'],
            ['name' => "Ibarapa north", 'state_id'=>'31'],
            ['name' => "Ido", 'state_id'=>'31'],
            ['name' => "Irepo", 'state_id'=>'31'],
            ['name' => "Iseyin", 'state_id'=>'31'],
            ['name' => "Itesiwaju", 'state_id'=>'31'],
            ['name' => "Iwajowa", 'state_id'=>'31'],
            ['name' => "Kajola", 'state_id'=>'31'],
            ['name' => "Lagelu", 'state_id'=>'31'],
            ['name' => "Ogbomoso north", 'state_id'=>'31'],
            ['name' => "Ogbomoso south", 'state_id'=>'31'],
            ['name' => "Ogo-oluwa", 'state_id'=>'31'],
            ['name' => "Olorunsogo", 'state_id'=>'31'],
            ['name' => "Oluyole", 'state_id'=>'31'],
            ['name' => "Ona-ara", 'state_id'=>'31'],
            ['name' => "Oorelope", 'state_id'=>'31'],
            ['name' => "Ori ire", 'state_id'=>'31'],
            ['name' => "Oyo east", 'state_id'=>'31'],
            ['name' => "Oyo west", 'state_id'=>'31'],
            ['name' => "Saki east", 'state_id'=>'31'],
            ['name' => "Saki west", 'state_id'=>'31'],
            ['name' => "Surulere", 'state_id'=>'31'],
            ['name' => "Barikin ladi", 'state_id'=>'32'],
            ['name' => "Bassa", 'state_id'=>'32'],
            ['name' => "Bokkos", 'state_id'=>'32'],
            ['name' => "Jos east", 'state_id'=>'32'],
            ['name' => "Jos north", 'state_id'=>'32'],
            ['name' => "Jos south", 'state_id'=>'32'],
            ['name' => "Kanam", 'state_id'=>'32'],
            ['name' => "Kanke", 'state_id'=>'32'],
            ['name' => "Langtang north", 'state_id'=>'32'],
            ['name' => "Langtang south", 'state_id'=>'32'],
            ['name' => "Mangu", 'state_id'=>'32'],
            ['name' => "Mikang", 'state_id'=>'32'],
            ['name' => "Pankshin", 'state_id'=>'32'],
            ['name' => "Qua'an pan", 'state_id'=>'32'],
            ['name' => "Riyom", 'state_id'=>'32'],
            ['name' => "Shendam", 'state_id'=>'32'],
            ['name' => "Wase", 'state_id'=>'32'],
            ['name' => "Abua-odual", 'state_id'=>'33'],
            ['name' => "Ahoada east", 'state_id'=>'33'],
            ['name' => "Ahoada west", 'state_id'=>'33'],
            ['name' => "Akuku toru", 'state_id'=>'33'],
            ['name' => "Andoni", 'state_id'=>'33'],
            ['name' => "Asari-toru", 'state_id'=>'33'],
            ['name' => "Bonny", 'state_id'=>'33'],
            ['name' => "Degema", 'state_id'=>'33'],
            ['name' => "Eleme", 'state_id'=>'33'],
            ['name' => "Emohua", 'state_id'=>'33'],
            ['name' => "Etche", 'state_id'=>'33'],
            ['name' => "Gokana", 'state_id'=>'33'],
            ['name' => "Ikwerre", 'state_id'=>'33'],
            ['name' => "Khana", 'state_id'=>'33'],
            ['name' => "Obio/akpor", 'state_id'=>'33'],
            ['name' => "Ogba/egbema/ndoni", 'state_id'=>'33'],
            ['name' => "Ogu/bolo", 'state_id'=>'33'],
            ['name' => "Okrika", 'state_id'=>'33'],
            ['name' => "Omuma", 'state_id'=>'33'],
            ['name' => "Opobo/nekoro", 'state_id'=>'33'],
            ['name' => "Oyigbo", 'state_id'=>'33'],
            ['name' => "Port harcourt", 'state_id'=>'33'],
            ['name' => "Tai", 'state_id'=>'33'],
            ['name' => "Binji", 'state_id'=>'34'],
            ['name' => "Bodinga", 'state_id'=>'34'],
            ['name' => "Dange/shuni", 'state_id'=>'34'],
            ['name' => "Gada", 'state_id'=>'34'],
            ['name' => "Goronyo", 'state_id'=>'34'],
            ['name' => "Gudu", 'state_id'=>'34'],
            ['name' => "Gwadabawa", 'state_id'=>'34'],
            ['name' => "Illela", 'state_id'=>'34'],
            ['name' => "Isa", 'state_id'=>'34'],
            ['name' => "Kebbe", 'state_id'=>'34'],
            ['name' => "Kware", 'state_id'=>'34'],
            ['name' => "Rabah", 'state_id'=>'34'],
            ['name' => "S/birni", 'state_id'=>'34'],
            ['name' => "Shagari", 'state_id'=>'34'],
            ['name' => "Silame", 'state_id'=>'34'],
            ['name' => "Sokoto north", 'state_id'=>'34'],
            ['name' => "Sokoto south", 'state_id'=>'34'],
            ['name' => "Tambuwal", 'state_id'=>'34'],
            ['name' => "Tangaza", 'state_id'=>'34'],
            ['name' => "Tureta", 'state_id'=>'34'],
            ['name' => "Wamakko", 'state_id'=>'34'],
            ['name' => "Wurno", 'state_id'=>'34'],
            ['name' => "Yabo", 'state_id'=>'34'],
            ['name' => "Ardo - kola", 'state_id'=>'35'],
            ['name' => "Bali", 'state_id'=>'35'],
            ['name' => "Donga", 'state_id'=>'35'],
            ['name' => "Gashaka", 'state_id'=>'35'],
            ['name' => "Gassol", 'state_id'=>'35'],
            ['name' => "Ibi", 'state_id'=>'35'],
            ['name' => "Jalingo", 'state_id'=>'35'],
            ['name' => "Karim-lamido", 'state_id'=>'35'],
            ['name' => "Kurmi", 'state_id'=>'35'],
            ['name' => "Lau", 'state_id'=>'35'],
            ['name' => "Sardauna", 'state_id'=>'35'],
            ['name' => "Takum", 'state_id'=>'35'],
            ['name' => "Ussa", 'state_id'=>'35'],
            ['name' => "Wukari", 'state_id'=>'35'],
            ['name' => "Yorro", 'state_id'=>'35'],
            ['name' => "Zing", 'state_id'=>'35'],
            ['name' => "Bade", 'state_id'=>'36'],
            ['name' => "Bursari", 'state_id'=>'36'],
            ['name' => "Damaturu", 'state_id'=>'36'],
            ['name' => "Fika", 'state_id'=>'36'],
            ['name' => "Fune", 'state_id'=>'36'],
            ['name' => "Geidam", 'state_id'=>'36'],
            ['name' => "Gujba", 'state_id'=>'36'],
            ['name' => "Gulani", 'state_id'=>'36'],
            ['name' => "Jakusko", 'state_id'=>'36'],
            ['name' => "Karasawa", 'state_id'=>'36'],
            ['name' => "Machina", 'state_id'=>'36'],
            ['name' => "Nangere", 'state_id'=>'36'],
            ['name' => "Nguru", 'state_id'=>'36'],
            ['name' => "Potiskum", 'state_id'=>'36'],
            ['name' => "Tarmuwa", 'state_id'=>'36'],
            ['name' => "Yunusari", 'state_id'=>'36'],
            ['name' => "Yusufari", 'state_id'=>'36'],
            ['name' => "Anka", 'state_id'=>'37'],
            ['name' => "Bakura", 'state_id'=>'37'],
            ['name' => "Birnin magaji", 'state_id'=>'37'],
            ['name' => "Bukkuyum", 'state_id'=>'37'],
            ['name' => "Bungudu", 'state_id'=>'37'],
            ['name' => "Gummi", 'state_id'=>'37'],
            ['name' => "Gusau", 'state_id'=>'37'],
            ['name' => "Kaura namoda", 'state_id'=>'37'],
            ['name' => "Maradun", 'state_id'=>'37'],
            ['name' => "Maru", 'state_id'=>'37'],
            ['name' => "Shinkafi", 'state_id'=>'37'],
            ['name' => "Talata mafara", 'state_id'=>'37'],
            ['name' => "Tsafe", 'state_id'=>'37'],
            ['name' => "Zurmi", 'state_id'=>'37'],
        ]);
    }
}
